integration:
  gis:
    connectTimeout: 5
    readTimeout: 30
  lmv:
    connectTimeout: 5
    readTimeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
resilience4j:
  circuitbreaker:
    instances:
      gis:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
      lmv:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
spring:
  application:
    name: api-precheck
  security:
    oauth2:
      client:
        registration:
          gis:
            authorization-grant-type: client_credentials
            provider: gis
          lmv:
            authorization-grant-type: client_credentials
            provider: lmv
springdoc:
  swagger-ui:
    operationsSorter: method
